apiVersion: 1

datasources:
  # 기본 데이터소스 (monitoring 테넌트)
  - name: Mimir-Monitoring
    type: prometheus
    access: proxy
    orgId: 1
    url: http://load-balancer:9009/prometheus
    isDefault: true
    version: 1
    editable: false
    # 최신 Grafana 헤더 설정 방식
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
      httpMethod: "GET"
      timeInterval: "30s"
      queryTimeout: "60s"
    secureJsonData:
      httpHeaderValue1: "monitoring"
    
  # OpenStack 워커 노드 테넌트
  - name: Mimir-OpenStack
    type: prometheus
    access: proxy
    orgId: 1
    url: http://load-balancer:9009/prometheus
    isDefault: false
    version: 1
    editable: false
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
      httpMethod: "GET"
      timeInterval: "30s"
      queryTimeout: "60s"
    secureJsonData:
      httpHeaderValue1: "openstack"
