apiVersion: 1

datasources:
  # 기본 데이터소스 (demo 테넌트)
  - name: Mimir-Demo
    type: prometheus
    access: proxy
    orgId: 1
    url: http://load-balancer:9009
    isDefault: true
    version: 1
    editable: false
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
      httpHeaderValue1: "demo"
    
  # 프로덕션 테넌트
  - name: Mimir-Production
    type: prometheus
    access: proxy
    orgId: 1
    url: http://load-balancer:9009
    isDefault: false
    version: 1
    editable: false
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
      httpHeaderValue1: "prod"
    
  # 스테이징 테넌트
  - name: Mimir-Staging
    type: prometheus
    access: proxy
    orgId: 1
    url: http://load-balancer:9009
    isDefault: false
    version: 1
    editable: false
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
      httpHeaderValue1: "staging"
    
  # 개발 테넌트
  - name: Mimir-Development
    type: prometheus
    access: proxy
    orgId: 1
    url: http://load-balancer:9009
    isDefault: false
    version: 1
    editable: false
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
      httpHeaderValue1: "dev"
    
  # 전체 테넌트 통합 뷰 (관리자용)
  - name: Mimir-All-Tenants
    type: prometheus
    access: proxy
    orgId: 1
    url: http://load-balancer:9009
    isDefault: false
    version: 1
    editable: false
    # 헤더 없이 설정하여 모든 테넌트 데이터 조회 (관리자 권한 필요)
