apiVersion: 1

datasources:
  # 기본 데이터소스 (demo 테넌트)
  - name: Mimir-Demo
    type: prometheus
    access: proxy
    orgId: 1
    url: http://load-balancer:9009/prometheus
    isDefault: true
    version: 1
    editable: false
    # 최신 Grafana 헤더 설정 방식
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
      httpMethod: "GET"
      timeInterval: "30s"
      queryTimeout: "60s"
    secureJsonData:
      httpHeaderValue1: "demo"
    
  # 프로덕션 테넌트
  - name: Mimir-Production
    type: prometheus
    access: proxy
    orgId: 1
    url: http://load-balancer:9009/prometheus
    isDefault: false
    version: 1
    editable: false
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
      httpMethod: "GET"
      timeInterval: "30s"
      queryTimeout: "60s"
    secureJsonData:
      httpHeaderValue1: "prod"
    
  # 스테이징 테넌트
  - name: Mimir-Staging
    type: prometheus
    access: proxy
    orgId: 1
    url: http://load-balancer:9009/prometheus
    isDefault: false
    version: 1
    editable: false
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
      httpMethod: "GET"
      timeInterval: "30s"
      queryTimeout: "60s"
    secureJsonData:
      httpHeaderValue1: "staging"
    
  # 개발 테넌트
  - name: Mimir-Development
    type: prometheus
    access: proxy
    orgId: 1
    url: http://load-balancer:9009/prometheus
    isDefault: false
    version: 1
    editable: false
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
      httpMethod: "GET"
      timeInterval: "30s"
      queryTimeout: "60s"
    secureJsonData:
      httpHeaderValue1: "dev"
