# Do not use this configuration in production.
# It is for demonstration purposes only.
# Run Mimir in single process mode, with all components running in 1 process.
target: all,alertmanager,overrides-exporter

# Configure Mimir to use Minio as object storage backend.
common:
  storage:
    backend: s3
    s3:
      endpoint: minio:9000
      access_key_id: mimir
      secret_access_key: supersecret
      insecure: true
      bucket_name: mimir

# Blocks storage requires a prefix when using a common object storage bucket.
blocks_storage:
  storage_prefix: blocks
  tsdb:
    dir: /data/ingester

# Use memberlist, a gossip-based protocol, to enable the 3 Mimir replicas to communicate
memberlist:
  join_members: [mimir-1, mimir-2, mimir-3]

ruler:
  rule_path: /data/ruler
  ring:
    # Quickly detect unhealthy rulers to speed up the tutorial.
    heartbeat_period: 2s
    heartbeat_timeout: 10s

# 외부 alertmanager 사용으로 내장 alertmanager 비활성화
# alertmanager:
#   data_dir: /data/alertmanager
#   fallback_config_file: /etc/alertmanager-fallback-config.yaml
#   external_url: http://localhost:9009/alertmanager

server:
  log_level: warn

# 다중 테넌시 설정
multitenancy_enabled: true

# 글로벌 제한사항 설정
limits:
  # 메트릭 수집 제한
  ingestion_rate: 10000                    # 초당 샘플 수
  ingestion_burst_size: 200000             # 버스트 크기
  max_series_per_metric: 50000             # 메트릭당 최대 시리즈 수
  max_series_per_user: 5000000             # 테넌트당 최대 시리즈 수
  max_samples_per_query: 50000000          # 쿼리당 최대 샘플 수
  
  # 쿼리 제한
  max_query_parallelism: 14                # 병렬 쿼리 수
  max_query_length: 32d                    # 최대 쿼리 범위
  
  # 저장 기간
  compactor_blocks_retention_period: 30d   # 블록 보존 기간
  
  # 라벨 제한
  max_label_name_length: 1024              # 라벨명 최대 길이
  max_label_value_length: 4096             # 라벨값 최대 길이
  max_label_names_per_series: 30           # 시리즈당 최대 라벨 수

# 테넌트별 오버라이드 설정
overrides:
  # 프로덕션 환경 테넌트
  prod:
    ingestion_rate: 20000
    max_series_per_user: 10000000
    compactor_blocks_retention_period: 90d
    
  # 스테이징 환경 테넌트  
  staging:
    ingestion_rate: 5000
    max_series_per_user: 1000000
    compactor_blocks_retention_period: 7d
    
  # 개발 환경 테넌트
  dev:
    ingestion_rate: 1000
    max_series_per_user: 100000
    compactor_blocks_retention_period: 3d
    
  # 데모 테넌트 (현재 사용 중)
  demo:
    ingestion_rate: 10000
    max_series_per_user: 2000000
    compactor_blocks_retention_period: 14d
