# Do not use this configuration in production.
# It is for demonstration purposes only.
# Run Mimir in single process mode, with all components running in 1 process.
target: all,alertmanager,overrides-exporter

# Configure Mimir to use Minio as object storage backend.
common:
  storage:
    backend: s3
    s3:
      endpoint: minio:9000
      access_key_id: mimir
      secret_access_key: supersecret
      insecure: true
      bucket_name: mimir

# Blocks storage requires a prefix when using a common object storage bucket.
blocks_storage:
  storage_prefix: blocks
  tsdb:
    dir: /data/ingester

# Use memberlist, a gossip-based protocol, to enable the 3 Mimir replicas to communicate
memberlist:
  join_members: [mimir-1:7946, mimir-2:7946, mimir-3:7946]
  bind_port: 7946
  advertise_port: 7946
  randomize_node_name: false

# Ingester ring configuration to fix InstancesCount issue
ingester:
  ring:
    # Quickly detect unhealthy ingesters
    heartbeat_period: 5s
    heartbeat_timeout: 15s
    # Use single instance for demo
    replication_factor: 1
    # Enable zone awareness for better distribution
    zone_awareness_enabled: false

ruler:
  rule_path: /data/ruler
  ring:
    # Quickly detect unhealthy rulers to speed up the tutorial.
    heartbeat_period: 2s
    heartbeat_timeout: 10s

# 외부 alertmanager 사용으로 내장 alertmanager 비활성화
# alertmanager:
#   data_dir: /data/alertmanager
#   fallback_config_file: /etc/alertmanager-fallback-config.yaml
#   external_url: http://localhost:9009/alertmanager

server:
  log_level: warn
  http_listen_port: 8080
  grpc_listen_port: 9095

# 다중 테넌시 설정
multitenancy_enabled: true

# 글로벌 제한사항 설정 (라벨 제한 대폭 증가)
limits:
  # 메트릭 수집 제한
  ingestion_rate: 10000                    # 초당 샘플 수
  ingestion_burst_size: 200000             # 버스트 크기
  
  # 쿼리 제한
  max_query_parallelism: 14                # 병렬 쿼리 수
  
  # 저장 기간
  compactor_blocks_retention_period: 30d   # 블록 보존 기간
  
  # 라벨 제한 (Container 메트릭 지원을 위해 대폭 증가)
  max_label_name_length: 1024              # 라벨명 최대 길이
  max_label_value_length: 4096             # 라벨값 최대 길이
  max_label_names_per_series: 100          # 메트릭당 최대 라벨 개수 (30 → 100)
  
  # 기타 제한사항
  max_global_series_per_user: 1000000      # 사용자당 최대 시리즈
  max_global_series_per_metric: 50000      # 메트릭당 최대 시리즈

# 런타임 설정 파일 지정 (테넌트별 오버라이드용)
runtime_config:
  file: /etc/mimir/runtime.yaml
