global:
  scrape_interval: 5s
  external_labels:
    cluster: demo
    namespace: demo

rule_files:
  - /etc/prometheus/rules.yaml

scrape_configs:
  - job_name: demo/mimir
    static_configs:
      - targets: ["mimir-1:8080"]
        labels:
          pod: "mimir-1"
      - targets: ["mimir-2:8080"]
        labels:
          pod: "mimir-2"
      - targets: ["mimir-3:8080"]
        labels:
          pod: "mimir-3"
          
  - job_name: 'central-node/system'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          instance: 'central-node'
          service: 'node-exporter'
          
  - job_name: 'central-node/containers'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          instance: 'central-node'
          service: 'cadvisor'

remote_write:
  - url: http://load-balancer:9009/api/v1/push
    headers:
      X-Scope-OrgID: monitoring
