# Mimir 런타임 설정 - 테넌트별 오버라이드
# 이 파일은 Mimir 실행 중에 동적으로 재로드됩니다.

# 테넌트별 제한사항 오버라이드
overrides:
  # 프로덕션 환경 테넌트
  prod:
    ingestion_rate: 20000
    ingestion_burst_size: 400000
    compactor_blocks_retention_period: 90d
    max_query_parallelism: 20
    max_label_names_per_series: 60
    
  # 스테이징 환경 테넌트  
  staging:
    ingestion_rate: 5000
    ingestion_burst_size: 100000
    compactor_blocks_retention_period: 7d
    max_query_parallelism: 10
    max_label_names_per_series: 60
    
  # 개발 환경 테넌트
  dev:
    ingestion_rate: 1000
    ingestion_burst_size: 20000
    compactor_blocks_retention_period: 3d
    max_query_parallelism: 5
    max_label_names_per_series: 60
    
  # 데모 테넌트 (기본 사용)
  demo:
    ingestion_rate: 10000
    ingestion_burst_size: 200000
    compactor_blocks_retention_period: 14d
    max_query_parallelism: 14 
    max_label_names_per_series: 60