# Mimir 런타임 설정 - 테넌트별 오버라이드
# 이 파일은 Mimir 실행 중에 동적으로 재로드됩니다.

# 테넌트별 제한사항 오버라이드
overrides:
  # OpenStack 워커 노드 테넌트
  openstack:
    ingestion_rate: 15000
    ingestion_burst_size: 300000
    compactor_blocks_retention_period: 60d
    max_query_parallelism: 15
    max_label_names_per_series: 80
    max_global_series_per_user: 2000000
    max_global_series_per_metric: 100000
    
  # 모니터링 테넌트 (기본 사용)
  monitoring:
    ingestion_rate: 10000
    ingestion_burst_size: 200000
    compactor_blocks_retention_period: 14d
    max_query_parallelism: 12
    max_label_names_per_series: 50